# Generated by Django 5.2.15 on 2026-06-09 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='ジャンル名')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
            ],
            options={
                'verbose_name': 'ジャンル',
                'verbose_name_plural': 'ジャンル',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='word',
            name='genre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='words', to='words.genre', verbose_name='ジャンル'),
        ),
    ]
